### ISSUE TITLE
Problem with the java version

### ISSUE THREAD

**Issue by AhmedMourad0** [issamalidev/num2a#1]
How am i supposed to implement it into my java program? The instructions at the readme are unclear to me .. keep getting UnsatisfiedLinkError with every attempt

**Comment by issamalidev** [comment]
Sorry if the readme file is not clear enough. I added this Java example to show how to use num2a in java applications. It's just for reference, when you want to use num2a (or any other native lib) in your Java application you have to write your own wrapper, actually each Java application needs its own wrapper, these are the JNI (Java Native Interface) rules, because Java applications can talk to native codes/libs through JNI. dealing with jni could be tricky if you are not familiar with this tech. here is a good reference about this subject: [http://www.javaworld.com/article/2077520/learn-java/java-tip-23--write-native-methods.html](http://www.javaworld.com/article/2077520/learn-java/java-tip-23--write-native-methods.html)

did you manage to compile the num2a Java example and test it?

**Comment by AhmedMourad0** [comment]
Not really, both the example and my implementation of the library are giving me this exception

![image](https://user-images.githubusercontent.com/29189251/27434430-f998dd88-5758-11e7-877b-c5eaf5d50b55.png)

**Comment by issamalidev** [comment]
the java wrapper (libjnum2a.so in my example) should be somewhere on your PATH or on a path listed in the java.library.path system property. Try to copy libjnum2a.so to /usr/lib. if you didn't link with num2a lib statically then libnum2a.a should be in your PATH too.

**Comment by AhmedMouradDev** [comment]
Can't find neither libjnum2a.so nor libnum2a.a

Sorry for my lack of exp in this topic, i'm actually an android dev but was kind of dragged into this project so just trying to work my way around
